var antalbiljetter, galnamusen, flygandekvasten, lustigahuset;
antalbiljetter = 20; 
galnamusen = Math.floor(antalbiljetter/3);
flygandekvasten = Math.floor(antalbiljetter/4); 
lustigahuset = Math.floor(antalbiljetter/2);

console.log("Åsa kan åka Galna Musen", galnamusen , "Gånger")
console.log("Åsa kan åka Flygande Kvasten", flygandekvasten, "gånger")
console.log("Åsa kan gå i lustiga huset", lustigahuset, "gånger")
